- daemon/examples/netns/daemonnodes.py
This example can be run as a standard user and by default connects to the localhost core-daemon. It will then create a number of nodes connected by a switch. It has a useful function that allows a command to be run on the remote node. In the example the first node pings the last one.
> Add an example which can run on the daemon when run as a standard user.

- scripts/core-daemon.service.in
On distributions using systemd, a default limit on the number of
tasks allowed to be created from a given unit may be set by default
(e.g., on F24, "DefaultTasksAccounting=yes" and "DefaultTasksMax=512"
are set in /etc/systemd/system.conf. A large CORE simulation may well
exceed that limit, at least during startup when many (sub)shell
processes are generated using fork().
To avoid running into this limit, set "TasksMax=infinity" in the
core-daemon.service unit file template.
> systemd: remove limit on fork() branching factor

- daemon/core/misc/xmlparser1.py
- daemon/core/services/quagga.py
- daemon/core/xen/xen.py
- daemon/examples/netns/emane80211.py
- daemon/examples/netns/howmanynodes.py
- daemon/ns3/examples/ns3wifirandomwalk.py
- doc/usage.rst
- gui/configs/sample1.imn
- gui/configs/sample10-kitchen-sink.imn
- gui/configs/sample3-bgp.imn
- gui/configs/sample4-nrlsmf.imn
- gui/configs/sample5-mgen.imn
- gui/configs/sample8-ipsec-service.imn
- gui/nodes.tcl
- gui/util.tcl
Since all Quagga daemons are configured from a consolidated
location (the 'zebra' service), there is nothing left to do
for a dedicated service such as 'vtysh'. This patch removes
the service, along with all references to it from the rest
of the source tree (sample *.imn files, examples, etc.)
> daemon: remove Quagga 'vtysh' service

- gui/widget.tcl
Simple bugfix to revive the Throughput Widget.
core-daemon uses e.g. "vetha.0.123" for n10 instead of "veth10.0.123". hex values == shorter interface names.
This updates the Tcl/Tk to match the Python.
> Bugfix/issue24 fix Throughput Widget

- packaging/rpm/core.spec.in
As of F25, the 'tc' command was moved to a separate sub-package of
iproute, which must be included both at build- and run-time.
> rpm: include iproute-tc [Build]Requires for fedora >= 25

- daemon/core/services/quagga.py
Allow native distribution packages to run with their default user
and group names by no longer forcing "-u root -g root" on any of
the Quagga daemons' command lines.
This should continue to allow hand-compiled and/or "side-loaded"
Quagga software to run as root, if configured to do so at build
time.
> daemon: start Quagga with default user/group names

- daemon/core/netns/vnode.py
Broadcast address is not set for IPv4 interfaces, this patch adds _"broadcast +"_ as a parameter to the _ip_ command.
> fix to add correct broadcast address for ipv4 interfaces 

- README.rst
- configure.ac
- daemon/core/bsd/netgraph.py
- daemon/core/bsd/nodes.py
- daemon/core/bsd/vnet.py
- daemon/core/bsd/vnode.py
- daemon/ns3/setup.py
- daemon/setup.py
- daemon/src/setup.py
- doc/man/core-cleanup.1
- doc/man/core-daemon.1
- doc/man/core-gui.1
- doc/man/core-xen-cleanup.1
- doc/man/coresendmsg.1
- doc/man/netns.1
- doc/man/vcmd.1
- doc/man/vnoded.1
- gui/initgui.tcl
- packaging/deb.mk
- packaging/deb/control
This PR simply updates the URLs and email addresses for the core-users and core-dev mailing lists.
NFC (no functional change)
----
update to:
https://publists.nrl.navy.mil/mailman/listinfo/core-users
https://publists.nrl.navy.mil/mailman/listinfo/core-dev
dev email:
core-dev@nrl.navy.mil
> globally replace mailing list URLs and dev email

- README.rst
Currently all of the commands show on the same line, which makes them fail with an error.  See on the main project page here on Github under `Build`.  I couldn't find a way to do it without the extra line break for the `.rst` file format.
> broke commands to separate lines

- configure.ac
This solves #128
gcc7 has a compatibility problem with python and issues a warning as described at https://bugzilla.redhat.com/show_bug.cgi?id=1473425  
Setting the `-Werror` flag treats all warnings as errors, which fails the build.  IMHO it is better to remove the flag from regular builds.  Advanced users can add it if they choose to.
> removed cflag -Werror

- gui/exec.tcl
Modify getMyIP to cache the local machine's IP address, and
return it without further accessing of the underlying resolver
libraries during subsequent invocations.
getMyIP is called roughly once a second from within monitor_loop
when refreshing CPU utilization in the bottom-right corner of
the GUI window. Other, dedicated CPU usage windows might also
call getMyIP at regular intervals.
With systemd commit cda458a54 (between v232 and v233), the
implementation of gethostbyname4_r() was updated to a more
intransigently standard-compliant error reporting convention,
which in turn causes glibc to retry in a more labor intensive
way (see https://github.com/systemd/systemd/pull/5359).
Under certain circumstances depending on the local hostname
and IP configuration, the glibc/systemd back-end …
> gui: exec.tcl: cache local IP address across calls to getMyIP

- daemon/sbin/core-daemon
- daemon/src/Makefile.am
- packaging/rpm/core.spec.in
First off, since v5 installs CORE python modules (core, corens3, netns) as .egg bundles, we need to explicitly use "pkg-resources.require()" in /usr/sbin/core-daemon before we can import from any of them.
Next, on x86_64, netns is installed to /usr/lib64/python*/site-packages, a.k.a. ${pyexecdir} (rather than simply ${pythondir}). If the former isn't part of $PYTHONPATH during install, "make install" fails for "daemon/src/Makefile".
Finally, there's an updated rpm .spec file sample that correctly identifes all dependencies required to build a proper RPM (using mock). Since the "logzero" package wasn't available as an RPM in the Fedora repositories, I added it myself here: https://bugzilla.redhat.com/show_bug.cgi?id=1514100
> Cleanup for building/installing v5 (and building RPMs of v5)

- daemon/core/netns/vnode.py
Currently, CORE unmounts per-container mountpoints *before* all daemons running inside the container are shut down. If any of those daemons attempt to access the filesystem during e.g. atexit(), they might damage the host filesystem instead.
Unmounting per-container mount points is unnecessary anyway, since the Linux kernel does that automaticallyonce the last process in a namespace is removed.
> Gls ns umount v2

- daemon/core/emulator/coreemu.py
This allows for a Python script that subclasses the EmuSession object.
For example:
```python
class HipSession(EmuSession):
''' ...insert custom code here
'''
session = coreemu.create_session(_cls=HipSession)
```
- allow passing in a Session class to CoreEmu.create_session() helper
Signed-off-by: Jeff Ahrenholz <siliconja@users.noreply.github.com>
> allow passing in a Session class to CoreEmu.create_session() helper

- configure.ac
This turns off docs build if the python-sphinx package is missing, instead of bombing out with an error.
- make python-sphinx optional
> make python-sphinx optional

- daemon/scripts/core-cleanup
Newer versions of killall (I'm using PSmisc 23.1 default with Ubuntu 18.04) require a "--ns" aka "namespace" option in order to properly kill vnoded. Otherwise the script silently fails to clean up anything.
This change allows the **core-cleanup** script to work with either version of killall (old and new) by first checking supported arguments.
Also use ip instead of brctl for destroying CORE-built bridges.
- fix core-cleanup script to invoke killall correctly
> fix core-cleanup script to invoke killall correctly

- configure.ac
- netns/Makefile.am
- ns3/Makefile.am
We have a certain test environment where we only want to build the **vnoded** and **vcmd** utilities. This adds a _./configure_ flag to only build the C utilities and makes the Python components optional.
Looking at the source, we have the following components: daemon (Python lib and daemon), docs (markdown), gui (Tcl/Tk), man (help2man), netns (C vcmd, vnoded utils), ns3 (Python), scripts (shell).
Following this change, one can build only the **netns** dir to get **vnoded** and **vcmd**, using the following configure syntax:
```
./configure \
--enable-vnodedonly=yes \
--disable-gui \
--disable-daemon \
--disable-python
```
-----
Commits: 
- add --enable-vnodedonly configure flag; make Python optional
> make-python-optional

- configure.ac
- daemon/Makefile.am
- docs/install.md
- ns3/Makefile.am
This causes PYTHONLIBDIR to be set to `/usr/local/lib/python3.6/dist-packages` under Ubuntu 18.04 when configured with `PYTHON=python3 ./configure`, which is in the default Python 3 search path.
Note that `/usr/lib/python3/dist-packages` is in this default path (so it works if you're configuring with `--prefix=/usr`), but the `/usr/local` path has `/usr/local/lib/python3.6/dist-packages`.
> fix #290 use pythondir var as base for setting PYTHONLIBDIR

- daemon/core/emulator/coreemu.py
See discussion here:
https://github.com/coreemu/core/pull/184
This is the same PR, now with the Session() class instead of the EmuSession() class.
> cherry-pick commit e56c001 for Session() instead of EmuSession() class

- daemon/core/api/tlv/corehandlers.py
This unbreaks the "File" > "Execute XML or Python script..." feature. This allows you to write a Python script that can run a standalone emulation (as root), or optionally add the scripted session to the core-daemon, to allow the GUI to connect to that session (as non-root user).
> fix exception when trying to run Python script from GUI

- install.sh
@bharnden sorry, I didn't catch this until a bit after submitting the earlier PR :)
But installing grpcio-tools should also happen the python3 (rather than legacy python2) way...
> update dependency installer to python3

- docs/install.md
- scripts/Makefile.am
The proper location for unit files is /usr/lib/systemd/system,
with /etc/systemd/system reserved for local overrides of default
package settings.
Signed-off-by: Gabriel Somlo <gsomlo@gmail.com>
> systemd: fix unit file install path

- daemon/core/gui/coreclient.py
- daemon/core/gui/dialogs/nodeservice.py
- daemon/core/gui/graph/graph.py
- daemon/core/gui/images.py
- daemon/core/gui/nodeutils.py
- right click + services on a custom node displays the service dialog with no current services (before it crashed)
- when a new custom node is drawn on the canvas, its services that configured before are added to node's core_node since they don't get added automatically
-  when reloading xml files with custom node, try to find and draw custom node's icon based on the .yaml file. If image file is not found in the icons directory, choose a default image for the custom icon.
- when choosing an image for custom node, if the image is not in the icons directory yet, warn the user and suggest user to drop a copy inside of the icons directory
> Coretk fix

- daemon/core/services/frr.py
Unlike Quagga, FRR requires 'staticd' to be running in order
to support provisioning and use of static routes in the running
configuration (e.g., 'ip route a.b.c.d/p nexthop').
> services/frr.py: frrboot.sh: start 'staticd' to support static routes

- daemon/core/gui/dialogs/wlanconfig.py
- daemon/core/gui/graph/edges.py
- daemon/core/gui/graph/graph.py
- daemon/core/gui/graph/node.py
- daemon/core/gui/nodeutils.py
- daemon/core/location/mobility.py
- when deleting a node during runtime state, if node is mdr, remove wireless links connected to that node, if node is a wireless network link (wlan/emane), remove the wireless links connected between the mdr nodes connected to that wlan or emane.
- when we configure wlan node, editing range value will start to draw range circles on mdrs connected to that wlan node, the circles update as range value changes
- add a logging.error to temporarily solve removing a wireless link when multiple wireless links exist between a pair of nodes
> Coretk enhance/wlanlink runtime deletion

- daemon/core/gui/coreclient.py
I'm importing and using DEFAULT_TERMS from a Python script.
I tried using the gnome-terminal command but it was missing this space character...
> fix typo in DEFAULT_TERMS make gnome-terminal work

- daemon/core/gui/coreclient.py
Fix quoting to allow gnome-terminal to launch properly under coretk-gui. Tested also with xterm OK.
Redid this branch + PR using the "git commit --no-verify" option to avoid isort mangling.
> fix #387 launch gnome-terminal properly by removing extra quoting try2

- daemon/scripts/core-cleanup
properly kill python3-based core-daemon when using 'core-cleanup -d'
> fix-core-cleanup-d-kill-daemon

- daemon/core/services/frr.py
Add staticd to the list of possible daemons to be started.
http://docs.frrouting.org/en/latest/setup.html#daemons-configuration-file
https://github.com/coreemu/core/issues/397
> Update frr.py to add staticd to daemons list

- daemon/core/emulator/session.py
- daemon/core/utils.py
We already support `/etc/core/environment` (system-wide) and `/home/user/.core/environment` (user-specific) environments. This adds a 3rd optional environment file: `/tmp/pycore.nnnnn/environment`.
The use case here is an automated build and testing system that spawns a new session. The code being tested under that system has been build under e.g. `myapp/build/usr/local/bin/myappd`, so the Python script that is building the session will automatically adjust the LD_SEARCH_PATH and PATH environment variables to reference e.g. `myapp/build/usr/local/bin` and `myapp/build/usr/local/lib`. 
In this manner, multiple of these test sessions may be running on the system simultaneously testing different builds of the software.
> add support for /tmp/pycore.nnnnn/environment file, DRY up env merges

- daemon/core/configservices/frrservices/services.py
- daemon/core/services/frr.py
- daemon/data/core.conf
Add the Fedora default location for FRR binaries (/usr/libexec/frr/*.)
to CORE's frrboot default "sbin" search path
Signed-off-by: Gabriel Somlo <gsomlo@gmail.com>
> frrboot: add fedora sbin path to default

- daemon/core/nodes/docker.py
Parsing `/proc/{self.pid}/environ` currently fails with "too many values to unpack (expected 2)" if any of the environment variables include `=` in the value, solve by splitting only on the first `=`.
> daemon: support environment variables containing = for docker nodes

- package/after-remove-deb.sh
- package/after-remove-rpm.sh
The uninstall scripts use the `sh` shell but -v is a command for a `bash` shell.
I have updated the scripts to use `! -z <environment variable>` as this returns true when the environment variable has any value. This is the same approach as the after-install scripts.
> Fixing package uninstall error

- daemon/core/gui/validation.py
- daemon/core/gui/widgets.py
Added ability to input negative config values in gui.
This is needed specifically for some emane models which have config parameters that may expect a negative value (fixedantennagain, txpower, etc.)
> Allow negative values in config frame
