coreemu/core

README.rst
I changed the READE to ReStructuredText so it looks nicer on github. I also added a direct link to the manual to avoid getting lost in the nrl site.
I left the google code link in where it was. That could probably be moved farther down.
=> Core readme update

daemon/core/services/quagga.py
Currently, all Quagga daemons are started concurrently by their
respective CORE services, using "quaggaboot.sh" generated by the
'zebra' service. However, all routing services depend on 'zebra'
already running, and 'vtysh' depends on ALL other Quagga services
before it can push configuration from the common "Quagga.conf" to
all running daemons (see "waitforvtyfiles()" in "quaggaboot.sh").
The spinwait+timeout based implementation of "waitforvtyfiles()"
may, depending on load, give up too early and fail to configure
all Quagga daemons.
This patch streamlines the way Quagga daemons are started, by
launching them all from the 'zebra' service. The correct sequence
is to first launch the 'zebra' daemon itself, then proceed with
all routing daemons, and finish with a call to "vtysh -b" which …
=> daemon: streamline Quagga startup

daemon/core/service.py
Will save someone some time in the future I'm sure...
=> Emit more descriptive error message if config file is incorrect

daemon/core/emulator/coreemu.py, daemon/core/netns/openvswitch.py, daemon/core/netns/vnet.py
The argument signature is wrong for update_link so cannot update the link or a running session.
=> update_link had wrong arg order

daemon/core/api/tlv/corehandlers.py, daemon/core/emulator/session.py, daemon/core/location/mobility.py, daemon/tests/conftest.py, daemon/tests/test_gui.py
* Added a few fixes that these tests help discover in messaging that wasn't typically used.
* Added link delete for network to node and node to network links
=> TLV Message Handling Tests

daemon/core/emane/emanemanager.py, daemon/core/emulator/emudata.py, daemon/core/emulator/enumerations.py, daemon/core/emulator/session.py, daemon/core/nodes/base.py, daemon/core/nodes/docker.py, daemon/core/nodes/interface.py, daemon/core/nodes/lxd.py, daemon/core/nodes/nodemaps.py, daemon/examples/docker/README.md, daemon/examples/docker/daemon.json, daemon/examples/docker/docker2core.py, daemon/examples/docker/docker2docker.py, daemon/examples/docker/switch.py, daemon/examples/lxd/README.md, daemon/examples/lxd/lxd2core.py, daemon/examples/lxd/lxd2lxd.py, daemon/examples/lxd/switch.py
Will add the possibility to use Docker and LXD to create Docker and LXC containers that can be stood up and linked to existing CORE nodes.
Will initially only be available through scripting and will have requirements of outside software/setup to be able to leverage these cases.
=> Adds Docker/LXD support

daemon/Pipfile, daemon/Pipfile.lock, daemon/core/__init__.py, daemon/scripts/core-daemon, docs/devguide.md
Also updated dev guide in documentation to provide guidance on setting up using pipenv.
=> Added development support for leveraging pipenv

daemon/requirements.txt
=> Bumping configparser to 4.0.2 in requirements.txt

daemon/core/xml/corexml.py
=> fix for custom services not setting service.configs when reading xml

daemon/core/xml/corexml.py, daemon/scripts/core-imn-to-xml
=> added imn-to-xml script

daemon/core/gui/coreclient.py, daemon/core/gui/dialogs/colorpicker.py, daemon/core/gui/dialogs/customnodes.py, daemon/core/gui/dialogs/nodeservice.py, daemon/core/gui/graph/edges.py, daemon/core/gui/graph/graph.py, daemon/core/gui/graph/node.py, daemon/core/gui/graph/shape.py, daemon/core/gui/menuaction.py, daemon/core/gui/menubar.py, daemon/core/gui/statusbar.py, daemon/core/gui/toolbar.py, daemon/core/gui/validation.py
- Add a menu option "Recent Files" to menubar, under File. This option shows the most recent files, clicking on a file opens that file
- Add a variable to CoreClient to keep track of nodes that have custom services. This will help differentiate newly created nodes and empty service nodes. Micro manage this variable when copy/paste nodes, delete nodes, reset data in CoreClient.
=> Coretk enhance/fix bug

daemon/core/gui/app.py, daemon/core/gui/dialogs/preferences.py, daemon/core/gui/themes.py, daemon/core/gui/validation.py
- allow editable scale entry field for setting the scale value manually
- add a scrollbar to allow scaling factor adjustment in increments of a specific value
- change node text and edge text to not scale as fast as other components
- choose a bigger size font for alert button text so that scaling can be seen more easily
=> Coretk enhance/scaling

daemon/core/gui/appconfig.py, daemon/core/gui/coreclient.py, daemon/core/gui/dialogs/executepython.py, daemon/core/gui/menubar.py
- Design Execute Script dialog 
- Use grpc call to execute script, redraw canvas and reset session data
- add /.coretk/scripts to store scripts for execution
=> Coretk enhance/execute xml script

daemon/core/gui/dialogs/preferences.py, daemon/core/gui/menuaction.py, daemon/core/gui/menubar.py
- allow terminals setting to be directly edited
- New Session deletes current session if it is not running, else prompt save session before creating a new session
- update current xml when saving xml, creating new session
- add Save As menu item to menubar
=> Coretk enhance/fix bugs

daemon/core/gui/dialogs/find.py, daemon/core/gui/dialogs/sessions.py, daemon/core/gui/menubar.py
- Create Find tool that allows user to search for a node by node's name.
- Circle the search result node in red and attempt to scroll the x-scrollbar and the y-scrollbar to the location of that node
- Touch up on session dialog's table: align header text with column text, bold header text so that it stands out and be more visible.
=> Pygui findfeature

daemon/core/api/tlv/corehandlers.py, daemon/core/emulator/session.py, daemon/core/nodes/base.py, daemon/core/nodes/network.py, daemon/core/nodes/physical.py, daemon/tests/test_nodes.py
…ific logic, refactored CoreNodeBase to have newnetif and for it to return the interface created
=> daemon: refactoring code inside session.add_link, session.update_link, session.delete_link

daemon/core/api/tlv/corehandlers.py, daemon/core/configservices/frrservices/services.py, daemon/core/configservices/quaggaservices/services.py, daemon/core/nodes/base.py, daemon/core/nodes/interface.py, daemon/core/nodes/network.py, daemon/core/nodes/physical.py, daemon/core/services/frr.py, daemon/core/services/quagga.py
Leveraging input and logic from #112 to help correct configurations for links
=> updates for link configuration to calculate a limit when bandwidth/delay are present

daemon/core/api/grpc/client.py, daemon/core/api/grpc/grpcutils.py, daemon/core/api/grpc/server.py, daemon/core/api/grpc/wrappers.py, daemon/core/api/tlv/corehandlers.py, daemon/core/configservices/quaggaservices/services.py, daemon/core/emane/emanemanager.py, daemon/core/emane/emanemodel.py, daemon/core/emane/linkmonitor.py, daemon/core/emane/models/bypass.py, daemon/core/emane/models/commeffect.py, daemon/core/emane/models/tdma.py, daemon/core/emane/nodes.py, daemon/core/emulator/sessionconfig.py, daemon/core/gui/dialogs/emaneconfig.py, daemon/core/nodes/netclient.py, daemon/core/xml/corexml.py, daemon/core/xml/emanexml.py, daemon/examples/grpc/emane80211.py, daemon/proto/core/api/grpc/core.proto, daemon/proto/core/api/grpc/emane.proto, daemon/scripts/core-cleanup, daemon/tests/test_grpc.py, daemon/tests/test_gui.py, docs/grpc.md, gui/wlan.tcl
Updates to launch EMANE daemons per nem.
=> EMANE process per nem

tasks.py
fixes issue #596 where the latest poetry version breaks installs
=> set poetry version to 1.1.7

docs/tutorials/common/grpc.md, docs/tutorials/tutorial1.md, docs/tutorials/tutorial2.md, docs/tutorials/tutorial3.md, docs/tutorials/tutorial5.md, docs/tutorials/tutorial6.md, docs/tutorials/tutorial7.md, mkdocs.yml
=> fix issues with updated documentation
